### ISSUE TITLE
PKGBUILD of cpan2aur2git

### ISSUE THREAD

**Issue by micwoj92** [bence98/cpan2aur2git#1]
Create PKGBUILD for the tool, additionally can be uploaded to AUR too.

**Comment by bence98** [comment]
https://aur.archlinux.org/packages/cpan2aur2git

**Comment by micwoj92** [comment]
Thanks, here are my suggestions to make it more correct:
```diff
diff --git a/PKGBUILD b/PKGBUILD
index 33fada7..7903124 100644
--- a/PKGBUILD
+++ b/PKGBUILD
@@ -2,17 +2,18 @@
 
 pkgname='cpan2aur2git'
 pkgver='0.0.1'
-pkgrel='1'
+pkgrel='2'
 pkgdesc="CPAN2AUR wrapper"
 arch=('any')
-url='https://github.com/bence98/cpan2aur2git'
+url="https://github.com/bence98/${pkgname}"
 license=('GPL-3.0-or-later')
 options=('!emptydirs')
-depends=()
-source=("$pkgname-$pkgver::git+https://github.com/bence98/cpan2aur2git.git#tag=v0.0.1")
+depends=('bash' 'perl-cpanplus-dist-arch' 'python-requests')
+makedepends=('git')
+source=("git+${url}#tag=v${pkgver}")
 md5sums=('SKIP')
 
 package() {
-	cd "$pkgname-$pkgver"
+	cd "$pkgname"
 	make DESTDIR="$pkgdir/" install
 }
```

**Comment by bence98** [comment]
Oh, shoot! Forgot about the `depends=()`! Thanks. Though `bash` is part of `base`, so there's no need to depend on it AFAIK. Similarly, if you're using AUR, you already have some form of Git.
I will apply the rest soon (tm).

**Comment by micwoj92** [comment]
git is required in makedepends for packages that use git to download sources.
Edit: also .SRCINFO needs updates to show these changes on aurweb.

**Comment by bence98** [comment]
Ah I see. I will add it then. And yes, Git told me about the `.SRCINFO` (rookie mistake, I know...)
